services:
- docker

language: cpp
dist: xenial
os: linux

git:
  autocrlf: false

addons:
  apt:
    sources:
      - sourceline: 'deb http://dl.bintray.com/igagis/ubuntu xenial main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x379CE192D401AB61'
    update: true
    packages:
    - binfmt-support
    - qemu-user-static
    - myci
  homebrew:
    update: true
    taps:
    - igagis/tap
    packages:
    - myci

jobs:
  include:
    - name: macosx
      os: osx
      compiler: clang
      osx_image: xcode11.3
    - name: ios
      os: osx
      compiler: clang
      osx_image: xcode11.3
    - name: android
      language: android
      android:
        components:
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-28
#          - sys-img-armeabi-v7a-android-22
          - extra-android-m2repository
    - name: msys2
      os: windows


env:
  global:
  # Encrypted MYCI_BINTRAY_API_KEY for publishing to bintray.
  - secure: "Bsnb0azM4w+B0BNeiME5D0AxJaa8hdOI8YWnfON2cU6Xhjs+JQ6hUKtgn/ckot4PRHsfPdxhYEND8AhV2ENJ4sd/fRIBxc+Va8KDZfvTuh9HGBWnwszH08XVR1rEymsy0kF5+NSyZ4IFq0RrSR3lKa1ULPN+liXyYNp+8hybzfPysvbRoQBzNgcmNECpzn9XD7BSKimi9qHtC3YEReWD/qy2f/oueb9OvZaMD6gQD+wB4+8uXh6AT4zvOnjGae30R1eCQNL5lCrXG0nPYLUlGPIM+96v+Ye3YMuRe75tvM8reOuLbLQj8x58+GTom4nZfbheWEnmGlplJiXYR9tTwFCQxmdLbKP0egeTgTBRGP90/5tOXZp8IFjXnY/CTA9IRnC5O+vP39UF7mj9htYUK5kLSKv5JadMCtb+6hl5i+KKoUDDY5lqHaxlIv13ClgAvfG8Fx2jB32RP76Xq5Kw37miQfalIvqGfRCjenGPQTYfBtyUUMIC1EVj/R1Z62O2lagUdA0iA0ZKI//PXaB16/gbHpvt3LgegG2WBkd0rzDIELMqx/tNa9lceTEYR7AO0ePHOWAlfBrnUA9+PIO8RjR2ljhkys9v4MDI5QGH2DSj5z4zB+7dFZVOrnRvrq0xft6lVEnVowR3S5gGEfJHiP130i5xZa5gMdjNyxdBNi0="
  # Encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap.
  - secure: "KzridCpsGqwZKHyUTep6ZyLggQN1q5xWUEAn1p27bqPaym9A2JVPYr2vIjAvrDL3Zs9gHlLyIATT/Ce8DgrhygfW3j0MT2Xv+grojvprgODNeyLk2j1KAUzxXn5Xg+VIa5SQwLJEY4U3C9nsn8w+w0uMcyCfeSYYvZi9NniUsH58qdZptWWcDaTM586EkMTWJK+6JCqoOcDPOyZIQxm1NQCiQFYgIOD1db+mwMm1dP78L3OO2nyBD9WRmXswdKSlqLSRimOFE3Qsrl2ArVP6OIEV6/MJs356y2mhyMINjnaKnNsH19t/FDZZMbbwyggk+rI7bxq5MZM3RxAtPOHYT1CPZ/8KorxnirkhLJ+I+Oa0wAQpytYJjEl4iFXW6lIZjTbeX+KHknTTyYeo6Tla/kIcyVyxahc6h1aYy05G8grUhlb2OQdGmeruRje0DKlVmZ/vF6hfVYlny10kN16nN12q9zw3qMykdWRfxQxlurBkofwjjLy1+vcedO/xqsH9rHIQ6SX5CBQ5mdn+gtvUxboT4KIj2I5E3Ycd95lpWLSfrz0amO/sJeg1fGLQWPZZ+96Tn5246WsTqEHiUDAVamZNepQTOAW794fpf8hLMwWiB2uds0HOe7PfMjaXhuAfXPZdgHnJRopopB3wjA24YADNIT86SGDPbp10TbOGKTE="
  - MYCI_GIT_USERNAME=igagis
  - PACKAGE_NAME=cssdom
  jobs:
# Ubuntu
  # - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=eoan OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
# Debian
  # - OS_REL=stretch OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=buster OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=buster OS=debian DOCKER_IMAGE=i386/$OS:$OS_REL PACKAGE_TYPE=deb
# Raspbian
  - OS_REL=stretch OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb
  # - OS_REL=stretch OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb


before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker run --name ccc -v $TRAVIS_BUILD_DIR/..:/build -w /build/$(basename $TRAVIS_BUILD_DIR) -it -d $DOCKER_IMAGE bash &&
    if [ "$PACKAGE_TYPE" == "deb" ]; then
      docker exec ccc apt update &&
      docker exec ccc apt install -y dirmngr &&
      docker exec ccc bash -c "echo 'deb http://dl.bintray.com/igagis/$OS $OS_REL main' > /etc/apt/sources.list.d/igagis.list" &&
      docker exec ccc apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
      docker exec ccc apt update &&
      docker exec ccc apt install -y devscripts equivs myci &&
      myci-deb-prepare.sh;
    fi;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    brew install prorab prorab-extra libutki libpapki libclargs;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$MYCI_GIT_USERNAME:$MYCI_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=xcode;
  fi
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    choco upgrade --no-progress -y msys2 &&
    export msys2="/c/tools/msys64/msys2_shell.cmd -defterm -no-start -msys -here -c" &&
    $msys2 "echo -e '[igagis_msys]\\nSigLevel = Optional TrustAll\\nServer = https://dl.bintray.com/igagis/msys2/msys' >> /etc/pacman.conf" &&
    $msys2 "echo -e '[igagis_mingw64]\\nSigLevel = Optional TrustAll\\nServer = https://dl.bintray.com/igagis/msys2/mingw64' >> /etc/pacman.conf" &&
    $msys2 "echo -e '[igagis_mingw32]\\nSigLevel = Optional TrustAll\\nServer = https://dl.bintray.com/igagis/msys2/mingw32' >> /etc/pacman.conf" &&
    $msys2 "pacman -Sy --noconfirm myci mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain";
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ] || [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export PACKAGE_VERSION=$(myci-deb-version.sh debian/changelog);
  fi

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc myci-deb-install-build-deps.sh;
  fi
# Accept android SDK licenses and install android tools
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    echo y | sdkmanager "ndk-bundle" &&
    echo y | sdkmanager "cmake;3.6.4111459";
  fi

before_script:
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
    chmod +x XcodeProjAdder &&
    (cd xcode/$PACKAGE_NAME && ../../XcodeProjAdder -XCP $PACKAGE_NAME.xcodeproj -SCSV `echo $(find ../../src -type f -name *.cpp) | sed -E -e 's/ /,/g'`)
  fi
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    $msys2 "myci-apply-version.sh -v \$(myci-deb-version.sh debian/changelog) msys2/PKGBUILD.in";
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc dpkg-buildpackage -us -uc;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    make &&
    make test;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    xcodebuild -workspace xcode/$PACKAGE_NAME.xcworkspace -scheme $PACKAGE_NAME CONFIGURATION_BUILD_DIR=../build -configuration Release &&
    myci-create-zip-package.sh -h src -f xcode/build/lib$PACKAGE_NAME.a///lib/ios -f LICENSE $PACKAGE_NAME-`myci-deb-version.sh debian/changelog`.zip;
  fi
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    (cd android && ./gradlew copy_aar) &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.pom.in &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
  fi
# running MSYS2 script from deployment provider did not work for some reason, so we do it here if the commit is a tagged one.
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    $msys2 "(cd msys2 && PKGEXT='.pkg.tar.xz' makepkg-mingw --syncdeps --noconfirm --skipinteg)" &&
    if [ ! -z "$TRAVIS_TAG" ]; then
      for f in $(find msys2 -name "mingw-w64-x86_64-$PACKAGE_NAME-*-any.pkg.*"); do
        $msys2 "myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw64 -d igagis_mingw64 $f";
      done &&
      for f in $(find msys2 -name "mingw-w64-i686-$PACKAGE_NAME-*-any.pkg.*"); do
        $msys2 "myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw32 -d igagis_mingw32 $f";
      done;
    fi;
  fi


before_deploy:


deploy:
- provider: script
  skip_cleanup: true
  on:
    tags: true
    condition: $PACKAGE_TYPE = deb && -z "$TRAVIS_JOB_NAME"
  script: myci-deploy-debian-bintray.sh -u igagis -r $OS -p $PACKAGE_NAME -c main -d $OS_REL $TRAVIS_BUILD_DIR/../*.deb
- provider: script
  skip_cleanup: true
  script: myci-deploy-maven-bintray.sh -u igagis -r android -d io/github/igagis -p $PACKAGE_NAME -v $PACKAGE_VERSION android/$PACKAGE_NAME-$PACKAGE_VERSION.aar
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = android
- provider: script
  skip_cleanup: true
  script: myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = macosx
- provider: script
  skip_cleanup: true
  script: myci-deploy-cocoapods.sh -r igagis -v `myci-deb-version.sh debian/changelog` -u igagis -b cocoapods -p $PACKAGE_NAME-`myci-deb-version.sh debian/changelog`.zip cocoapods/$PACKAGE_NAME.podspec.in
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = ios
